/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionInquiry {
  'email' : string,
  'childAge' : bigint,
  'programInterest' : string,
  'timestamp' : Time,
  'phone' : string,
  'childName' : string,
  'parentName' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllAdmissionInquiries' : ActorMethod<[], Array<AdmissionInquiry>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'submitAdmissionInquiry' : ActorMethod<
    [string, string, bigint, string, string, string],
    undefined
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];